### ISSUE TITLE
Add C# versions to the examples

### ISSUE THREAD

**Issue by LyudvaDmitry** [ttu/kotlin-is-like-csharp#14]
Hey!
It would be really great to see which features are available starting from which version in C#.

Why is it useful? At the moment of posting Unity uses C# 9.0, Godot uses C# 8.0. I am sure there are also non-gamedev projects out there that are locked with old versions of C#. So if someone wants to switch from Kotlin to C# (or try gamedev like me), it would really help them to understand what can be expected from older versions of C# as well.

Thanks for this project by the way, C# now looks way more attractive to me.

**Comment by ttu** [comment]
Hi. This is actually a good idea that we could make more clear in the examples. Currently there is a mention if code requires C# 9, e.g.
```cs
// Pre C# 9
var nb = 42;
var text = nb switch
{
    int i when i < 10 => "single digit",
    10 => "double digits",
    int i when i < 100 => "double digits",
    int i when i < 1000 => "triple digits",
    _ => "four or more digits"
};

// With C# 9 relational and conjunctive patterns
var nb = 42;
var text = nb switch
{
    < 10 => "single digit",
    10 or (>= 11 and < 100) => "double digits",
    < 1000 => "triple digits",
    _ => "for or more digits",
};
```
C# 8 was release 2019, so I think there is no need to mention if code requires C#8.

I will close this issue, but we will keep in mind that we will make this even more clear with future changes.

**Comment by ttu** [comment]
Mostly new features in C#10 and 11 are for more specific use cases, e.g. additions to pattern matching, but for example this might be a good addition to some example
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#list-patterns
